#!/usr/bin/env bash
set -e

main() {
  declare ARGS=("$@")
  if [[ -n "$SEMVER_GENERATOR_INPUT" ]] && [[ -n "$SEMVER_GENERATOR_BUMP" ]]; then
    ARGS=("--input" "$SEMVER_GENERATOR_INPUT" "--bump" "$SEMVER_GENERATOR_BUMP")
  fi

  if [ ${#ARGS[@]} -eq 0 ]; then
    echo "No arguments provided for bumping version" >&2
    exit 1
  fi

  if ! /usr/local/bin/semver "${ARGS[@]}" >/dev/null; then
    exit 1
  fi

  BUMPED_VERSION="$(/usr/local/bin/semver "${ARGS[@]}")"
  echo "$BUMPED_VERSION"
  if [ -n "$GITHUB_OUTPUT" ]; then
    echo "BUMPED_VERSION=$BUMPED_VERSION" >>"$GITHUB_OUTPUT"
  fi
}

main "$@"
