#!/usr/bin/env sh

if [ -n "$INPUT_VERSION" ] && [ -n "$INPUT_BUMP" ]; then
  /usr/local/bin/semver-generator --bump "$INPUT_BUMP" --input "$INPUT_VERSION"
else
  /usr/local/bin/semver-generator "$@"
fi
