---
name: "lint"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf

  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Run markdown-lint
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
        with:
          config: ".github/linters/.markdown-lint.yml"
          args: "./README.md"

  yamllint:
    name: yamllint
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c
        with:
          config_file: ".github/linters/.yamllint.yml"
